module.exports = {
  Cemetery: require('./Cemetery'),
  Section: require('./Section'),
  Plot: require('./Plot'),
  Crematorium: require('./Crematorium'),
  Deceased: require('./Deceased'),
  BurialEvent: require('./BurialEvent'),
  Owner: require('./Owner'),
  Ownership: require('./Ownership'),
  Booking: require('./Booking'),
  Exhumation: require('./Exhumation'),
  Monument: require('./Monument'),
  Tariff: require('./Tariff'),
  ServiceCharge: require('./ServiceCharge'),
  WorkOrder: require('./WorkOrder'),
  Enquiry: require('./Enquiry'),
  User: require('./User'),
  Role: require('./Role'),
  AuditLog: require('./AuditLog'),
  Document: require('./Document'),
  Undertaker: require('./Undertaker'),
  Notification: require('./Notification'),
};
